# Generated by Django 5.2.3 on 2025-06-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitemconfig_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemconfig',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
