# Generated by Django 5.2 on 2025-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_en",
            field=models.TextField(null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_uz",
            field=models.TextField(null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="post",
            name="description_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Short description"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="description_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Short description"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
