# Generated by Django 5.2 on 2025-05-04 19:31

import apps.user.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.managers.CustomUserManager()),
            ],
        ),
    ]
