# Generated by Django 5.2 on 2025-05-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=150, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Contact message",
                "verbose_name_plural": "Contact messages",
            },
        ),
    ]
